"""empty message

Revision ID: 3abd1334d659
Revises: c15130cb7363
Create Date: 2019-10-29 13:44:05.377726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3abd1334d659'
down_revision = 'c15130cb7363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('course_instructor_key', 'course', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('course_instructor_key', 'course', ['instructor'])
    # ### end Alembic commands ###
