"""empty message

Revision ID: 5913c4f518a3
Revises: d0ac4bcb1314
Create Date: 2019-11-18 23:05:02.601144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5913c4f518a3'
down_revision = 'd0ac4bcb1314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('marks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'marks')
    # ### end Alembic commands ###
