"""empty message

Revision ID: 99af581ae6e4
Revises: f3f7bbeffd7c
Create Date: 2019-11-09 14:32:57.545485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99af581ae6e4'
down_revision = 'f3f7bbeffd7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('title', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'title')
    # ### end Alembic commands ###
