"""..

Revision ID: d0e10d07527d
Revises: cbee473cb85d
Create Date: 2019-10-22 09:11:49.465410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e10d07527d'
down_revision = 'cbee473cb85d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('access', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'access')
    # ### end Alembic commands ###
