"""empty message

Revision ID: f11d4c7d323b
Revises: 3abd1334d659
Create Date: 2019-10-31 13:59:40.331851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f11d4c7d323b'
down_revision = '3abd1334d659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_course_title', table_name='course')
    op.create_index(op.f('ix_course_title'), 'course', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_title'), table_name='course')
    op.create_index('ix_course_title', 'course', ['title'], unique=False)
    # ### end Alembic commands ###
