"""great avalanche

Revision ID: f3f7bbeffd7c
Revises: f11d4c7d323b
Create Date: 2019-11-01 16:59:12.585595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f7bbeffd7c'
down_revision = 'f11d4c7d323b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationship_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    op.drop_table('members')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='members_course_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='members_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='members_pkey')
    )
    op.drop_table('relationship_table')
    # ### end Alembic commands ###
